#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/asmvik/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# copied and modified from https://medium.com/@khhini/yabai-a-tilling-window-manager-for-macos-03822421250c

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Discord$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^MacPass$" manage=off
yabai -m rule --add app="^IINA$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --apply

yabai -m config layout bsp
yabai -m config window_placement second_child

# Padding
yabai -m config external_bar all:40:0
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config right_padding 8
yabai -m config left_padding 8
yabai -m config window_gap 8

# mouse settings
# yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack

echo "yabai configuration loaded.."
